### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by christianschneider89** [maechler/sna#2]
2015-11-17 10:01:59 INFO  NewsportalFetcher:37 - Fetched newsportal tagesanzeiger
2015-11-17 10:01:59 INFO  NewsportalFetcher:37 - Fetched newsportal watson_news
2015-11-17 10:01:59 INFO  NewsportalFetcher:37 - Fetched newsportal Weltwoche
2015-11-17 10:01:59 INFO  NewsportalFetcher:37 - Fetched newsportal blickamabend
2015-11-17 10:01:59 INFO  NewsportalFetcher:37 - Fetched newsportal Blickch
2015-11-17 10:01:59 INFO  NewsportalFetcher:37 - Fetched newsportal NZZ
2015-11-17 10:02:00 INFO  NewsportalFetcher:37 - Fetched newsportal 20min
2015-11-17 10:02:16 INFO  NewsportalFetcher:75 - Fetched users for newsportal tagesanzeiger (3828)
2015-11-17 10:02:26 INFO  NewsportalFetcher:75 - Fetched users for newsportal watson_news (2175)
2015-11-17 10:02:37 INFO  NewsportalFetcher:75 - Fetched users for newsportal Weltwoche (2429)
2015-11-17 10:03:03 INFO  NewsportalFetcher:75 - Fetched users for newsportal blickamabend (5772)
2015-11-17 10:03:18 INFO  NewsportalFetcher:68 - TwitterException:  Rate limit exceeded
2015-11-17 10:03:18 INFO  NewsportalFetcher:69 - Sleeping for  16min
2015-11-17 10:19:30 INFO  NewsportalFetcher:75 - Fetched users for newsportal Blickch (6419)
2015-11-17 10:20:12 INFO  NewsportalFetcher:75 - Fetched users for newsportal NZZ (9500)
2015-11-17 10:20:38 INFO  NewsportalFetcher:68 - TwitterException:  Rate limit exceeded
2015-11-17 10:20:38 INFO  NewsportalFetcher:69 - Sleeping for  16min
2015-11-17 10:36:59 INFO  NewsportalFetcher:75 - Fetched users for newsportal 20min (10660)
2015-11-17 10:36:59 INFO  NewsportalFetcher:78 - Fetched all users for every newsportal
2015-11-17 10:36:59 INFO  NewsportalGephiExport:79 - Creating gephi Graph
2015-11-17 10:36:59 INFO  NewsportalGephiExport:102 - Creating nodes
2015-11-17 10:36:59 INFO  NewsportalGephiExport:104 - Creating edges
Exception in thread "main" java.lang.IllegalStateException: Source and Target must not be null. Every node must be added to network as a node before using it as a edge.
    at ch.fhnw.sna.twitter.NewsportalGephiExport.createOrUpdateEdge(NewsportalGephiExport.java:178)
    at ch.fhnw.sna.twitter.NewsportalGephiExport.createEdges(NewsportalGephiExport.java:168)
    at ch.fhnw.sna.twitter.NewsportalGephiExport.createGraph(NewsportalGephiExport.java:105)
    at ch.fhnw.sna.twitter.NewsportalGephiExport.export(NewsportalGephiExport.java:80)
    at ch.fhnw.sna.twitter.NewsportalFetcher_Main.main(NewsportalFetcher_Main.java:33)

**Comment by christianschneider89** [comment]
Funktioniert nun.
Graph File erfolgreich erstellt.
